# Generated by Django 3.0.6 on 2020-06-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=78)),
            ],
        ),
        migrations.CreateModel(
            name='todoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Text', models.CharField(max_length=400)),
                ('create_date', models.DateTimeField(verbose_name='Date Created')),
                ('Priority', models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HI', 'High')], default='LW', max_length=6)),
                ('Colour', models.CharField(choices=[('WHT', 'White'), ('BLK', 'Black'), ('GRY', 'Grey'), ('RED', 'Red'), ('GRN', 'Green'), ('BLE', 'Blue'), ('YLW', 'Yellow'), ('VLT', 'Violet'), ('PRL', 'Purple'), ('ORN', 'Orange'), ('BRN', 'Brown')], default='WHT', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todouser')),
            ],
        ),
    ]
